version: '2.2'

services:
  traefik:
    container_name: traefik
    image: traefik
    environment:
      - 'VIRTUAL_HOST=${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'VIRTUAL_PORT=8080'
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - reverse-proxy
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${COMPOSE_PROJECT_DIR}/.docker/.ca-certificates:/ca-certs
      - ${COMPOSE_PROJECT_DIR}/traefik.toml:/traefik.toml
      - ${COMPOSE_PROJECT_DIR}/acme.json:/acme.json
      - ${COMPOSE_PROJECT_DIR}/config:/config
      - ${DOCKER_DEVBOX_CERTS_PATH}:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}"
      - "traefik.port=8080"
networks:
  reverse-proxy:
    external: true
    name: ${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}
